[package]
name = "weather"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
chrono-tz = "0.10.3"
serde = { version = "1.0.219", features = ["derive"] }
ureq = { version = "3.0.12", features = ["json"] }
